
-- 로그인
SELECT MEMBER_NAME, MEMBER_ID, MEMBER_PW, MEMBER_PHONE, DELETE_FL, ENROLL_DATE,
MEMBER_EMAIL, MEMBER_GENDER,MEMBER_BIRTH,EMAIL_FL,SMS_FL,AUTHORITY
FROM MEMBER;

-- 회원2생성
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL,'회원1','user02','pass02','01098749078',DEFAULT,DEFAULT,
'user020@naver.com','M','1995-03-10','N','N','1' );

-- 회원생성 디폴트
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL,'홍길동','user01','pass01','01011111111',DEFAULT,DEFAULT,
'user01@naver.com','F','1998-01-16','N','N','1');

-- 비밀번호 암호화로 바꾸기
UPDATE "MEMBER" SET
MEMBER_PW = '$2a$10$21OFTjNEoc7AIHhG5agN5eLTZ4mtnEMob7lEH2qHHQGTB445Z2xXK'
WHERE MEMBER_NAME ='유저이';

-- ★ 로그인 SQL
SELECT MEMBER_NAME, MEMBER_ID, MEMBER_PW, MEMBER_PHONE, DELETE_FL, 
  		TO_CHAR(ENROLL_DATE,'YYYY"년" MM"월" DD"일" HH24 "시" MI"분" SS"초"') AS ENROLL_DATE,
		MEMBER_EMAIL, MEMBER_GENDER,MEMBER_BIRTH,EMAIL_FL,SMS_FL,AUTHORITY
		FROM MEMBER
		WHERE DELETE_FL='N'
		AND MEMBER_ID= 'user02'
		
DELETE 
FROM "MEMBER"
WHERE MEMBER_PHONE ='01098749078'

SELECT * FROM "MEMBER" 