CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_PHONE"	CHAR(11)		NOT NULL,
	"DELETE_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_GENDER"	CHAR(1)		NOT NULL,
	"MEMBER_BIRTH"	DATE		NOT NULL,
	"EMAIL_FL"	CHAR(1)		NOT NULL,
	"SMS_FL"	CHAR(1)		NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호(암호화 진행)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '휴대폰 번호(- 없음)';

COMMENT ON COLUMN "MEMBER"."DELETE_FL" IS '탈퇴여부(N:탈퇴X, Y:탈퇴O)';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원 생일';

COMMENT ON COLUMN "MEMBER"."EMAIL_FL" IS '회원 이메일 수신 동의(Y:수신동의, N:수신 비동의)';

COMMENT ON COLUMN "MEMBER"."SMS_FL" IS '회원 SMS 수신 동의(Y:수신동의, N:수신 비동의)';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원 권한(1: 일반, 2:관리자)';

CREATE TABLE "BOOK" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"BOOK_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHECK_IN"	DATE		NOT NULL,
	"CHECK_OUT"	DATE		NOT NULL,
	"ROOM_PROCESS"	NUMBER		NOT NULL,
	"ROOM_CANCEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOOK_CARD_NO"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GUEST_NO"	NUMBER		NOT NULL,
	"ROOM_NUM"	NUMBER		NOT NULL,
	"PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOOK"."BOOK_NO" IS '예약 번호(SEQ_BOOK_NO)';

COMMENT ON COLUMN "BOOK"."BOOK_DATE" IS '예약 완료 날짜';

COMMENT ON COLUMN "BOOK"."CHECK_IN" IS '체크인 날짜';

COMMENT ON COLUMN "BOOK"."CHECK_OUT" IS '체크아웃 날짜';

COMMENT ON COLUMN "BOOK"."ROOM_PROCESS" IS '예약 진행 상태(-1:취소, 0:예약신청, 1:결제완료)';

COMMENT ON COLUMN "BOOK"."ROOM_CANCEL_FL" IS '예약 취소 여부(N:취소X, Y:취소O)';

COMMENT ON COLUMN "BOOK"."BOOK_CARD_NO" IS '예약 카드 번호';

COMMENT ON COLUMN "BOOK"."MEMBER_NO" IS '예약한 회원 번호';

COMMENT ON COLUMN "BOOK"."GUEST_NO" IS '예약한 비회원 번호';

COMMENT ON COLUMN "BOOK"."ROOM_NUM" IS '예약한 호수';

COMMENT ON COLUMN "BOOK"."PRICE" IS '예약 금액';

CREATE TABLE "ROOM_TYPE" (
	"ROOM_TYPE_NO"	NUMBER		NOT NULL,
	"ROOM_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ROOM_TYPE"."ROOM_TYPE_NO" IS '객실 타입 번호';

COMMENT ON COLUMN "ROOM_TYPE"."ROOM_NAME" IS '객실 이름';

CREATE TABLE "MEETING" (
	"MEETING_NO"	NUMBER		NOT NULL,
	"MEETING_NAME"	VARCHAR2(20)		NOT NULL,
	"MEETING_MEMBER_MAX"	NUMBER		NOT NULL,
	"MEETING_DATE"	DATE		NOT NULL,
	"MEETING_MEM_NAME"	VARCHAR2(20)		NOT NULL,
	"MEETING_PROCESS"	NUMBER		NOT NULL,
	"MEETING_CANCEL_FL"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "MEETING"."MEETING_NO" IS '미팅룸 번호';

COMMENT ON COLUMN "MEETING"."MEETING_NAME" IS '미팅룸 이름';

COMMENT ON COLUMN "MEETING"."MEETING_MEMBER_MAX" IS '미팅룸 수용인원';

COMMENT ON COLUMN "MEETING"."MEETING_DATE" IS '미팅룸 예약일';

COMMENT ON COLUMN "MEETING"."MEETING_MEM_NAME" IS '미팅룸 예약자명';

COMMENT ON COLUMN "MEETING"."MEETING_PROCESS" IS '미팅룸 예약 진행상태';

COMMENT ON COLUMN "MEETING"."MEETING_CANCEL_FL" IS '미팅룸 예약 취소 여부(N: 예약 취소X,Y: 예약 취소O)';

CREATE TABLE "GUEST" (
	"GUEST_NO"	NUMBER		NOT NULL,
	"GUEST_NAME"	VARCHAR2(20)		NOT NULL,
	"GUEST_EMAIL"	VARCHAR2(50)		NOT NULL,
	"GUEST_PHONE"	CHAR(11)		NOT NULL
);

COMMENT ON COLUMN "GUEST"."GUEST_NO" IS '비회원 번호(SEQ_GUEST_NO)';

COMMENT ON COLUMN "GUEST"."GUEST_NAME" IS '비회원 이름';

COMMENT ON COLUMN "GUEST"."GUEST_EMAIL" IS '비회원 이메일';

COMMENT ON COLUMN "GUEST"."GUEST_PHONE" IS '비회원 휴대폰 번호(- 없음)';

CREATE TABLE "ADD" (
	"ADD_MARRIED_FL"	CHAR(1)	DEFAULT 'N'	NULL,
	"ADD_TEL"	VARCHAR2(11)		NULL,
	"ADD_ADDRESS"	VARCHAR2(100)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ADD"."ADD_MARRIED_FL" IS '결혼여부(N:결혼X, Y:결혼O)';

CREATE TABLE "ROOM_VIEW" (
	"ROOM_VIEW_NO"	NUMBER		NOT NULL,
	"ROOM_VIEW_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ROOM_VIEW"."ROOM_VIEW_NO" IS '전망 번호';

COMMENT ON COLUMN "ROOM_VIEW"."ROOM_VIEW_NAME" IS '전망 이름';

CREATE TABLE "PAYMENT" (
	"CARD_NO"	VARCHAR2(20)		NOT NULL,
	"CARD_OWNER"	VARCHAR2(20)		NOT NULL,
	"CARD_TYPE"	VARCHAR2(20)		NOT NULL,
	"CARD_EXPIRE_DATE"	CHAR(4)		NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."CARD_NO" IS '결제 카드번호';

COMMENT ON COLUMN "PAYMENT"."CARD_OWNER" IS '결제 카드 소유자명';

COMMENT ON COLUMN "PAYMENT"."CARD_TYPE" IS '결제 카드 종류';

COMMENT ON COLUMN "PAYMENT"."CARD_EXPIRE_DATE" IS '결제 카드 만료일자';

CREATE TABLE "OPTION" (
	"OPTION_NO"	NUMBER		NOT NULL,
	"OPTION_NAME"	VARCHAR2(50)		NOT NULL,
	"OPTION_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "OPTION"."OPTION_NO" IS '옵션 번호(SEQ_OPTION_NO)';

COMMENT ON COLUMN "OPTION"."OPTION_NAME" IS '옵션 이름';

COMMENT ON COLUMN "OPTION"."OPTION_PRICE" IS '옵션 가격';

CREATE TABLE "ROOM" (
	"ROOM_NUM"	NUMBER		NOT NULL,
	"BOOK_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ROOM_TYPE_NO"	NUMBER		NOT NULL,
	"ROOM_VIEW_NO"	NUMBER		NOT NULL,
	"ROOM_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ROOM"."ROOM_NUM" IS '객실 호수';

COMMENT ON COLUMN "ROOM"."BOOK_FL" IS '객실 예약 여부(N:예약O, Y:예약X)';

COMMENT ON COLUMN "ROOM"."ROOM_TYPE_NO" IS '객실 타입 번호';

COMMENT ON COLUMN "ROOM"."ROOM_VIEW_NO" IS '객실 전망 번호';

COMMENT ON COLUMN "ROOM"."ROOM_PRICE" IS '객실 가격';

CREATE TABLE "CMM" (
	"CMM_NO"	NUMBER		NOT NULL,
	"CMM_TITLE"	VARCHAR2(100)		NOT NULL,
	"CMM_SUB"	VARCHAR2(300)		NOT NULL,
	"CMM_TITLE_IMG"	VARCHAR2(200)		NOT NULL,
	"CMM_CON_IMG"	VARCHAR2(200)		NOT NULL,
	"CMM_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "CMM"."CMM_NO" IS '공지사항 번호(SEQ_CMM_NO)';

COMMENT ON COLUMN "CMM"."CMM_TITLE" IS '공지사항 제목';

COMMENT ON COLUMN "CMM"."CMM_SUB" IS '공지사항 세부';

COMMENT ON COLUMN "CMM"."CMM_TITLE_IMG" IS '공지사항 제목 사진 경로';

COMMENT ON COLUMN "CMM"."CMM_CON_IMG" IS '공지사항 내용 사진 경로';

COMMENT ON COLUMN "CMM"."CMM_DEL_FL" IS '공지사항 삭제 여부(N:삭제O, Y:삭제X)';

CREATE TABLE "PROMOTION" (
	"PROMOTION_NO"	NUMBER		NOT NULL,
	"PROMOTION_TITLE"	VARCHAR2(100)		NOT NULL,
	"PROMOTION_SUB"	VARCHAR2(300)		NOT NULL,
	"PROMOTION_TITLE_IMG"	VARCHAR2(200)		NOT NULL,
	"PROMOTION_CON_IMG"	VARCHAR2(200)		NOT NULL,
	"PROMOTION_DATE"	VARCHAR2(100)		NOT NULL,
	"PROMOTION_PRICE"	NUMBER		NOT NULL,
	"PROMOTION_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "PROMOTION"."PROMOTION_NO" IS '프로모션 번호(SEQ_PROMOTION_NO)';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_TITLE" IS '프로모션 제목';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_SUB" IS '프로모션 세부';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_TITLE_IMG" IS '프로모션 제목 사진 경로';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_CON_IMG" IS '프로모션 내용 사진 경로';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_DATE" IS '프로모션 기간';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_PRICE" IS '프로모션 가격';

COMMENT ON COLUMN "PROMOTION"."PROMOTION_DEL_FL" IS '프로모션 삭제 여부(N:삭제O, Y:삭제X)';

CREATE TABLE "BOOK_OPTION" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"OPTION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"OPTION_CNT"	NUMBER		NULL
);

COMMENT ON COLUMN "BOOK_OPTION"."BOOK_NO" IS '예약 번호';

COMMENT ON COLUMN "BOOK_OPTION"."OPTION_FL" IS '예약에 옵션이 있는지';

COMMENT ON COLUMN "BOOK_OPTION"."OPTION_CNT" IS '예약 옵션 수량';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (
	"BOOK_NO"
);

ALTER TABLE "ROOM_TYPE" ADD CONSTRAINT "PK_ROOM_TYPE" PRIMARY KEY (
	"ROOM_TYPE_NO"
);

ALTER TABLE "MEETING" ADD CONSTRAINT "PK_MEETING" PRIMARY KEY (
	"MEETING_NO"
);

ALTER TABLE "GUEST" ADD CONSTRAINT "PK_GUEST" PRIMARY KEY (
	"GUEST_NO"
);

ALTER TABLE "ROOM_VIEW" ADD CONSTRAINT "PK_ROOM_VIEW" PRIMARY KEY (
	"ROOM_VIEW_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"CARD_NO"
);

ALTER TABLE "OPTION" ADD CONSTRAINT "PK_OPTION" PRIMARY KEY (
	"OPTION_NO"
);

ALTER TABLE "ROOM" ADD CONSTRAINT "PK_ROOM" PRIMARY KEY (
	"ROOM_NUM"
);

ALTER TABLE "CMM" ADD CONSTRAINT "PK_CMM" PRIMARY KEY (
	"CMM_NO"
);

ALTER TABLE "PROMOTION" ADD CONSTRAINT "PK_PROMOTION" PRIMARY KEY (
	"PROMOTION_NO"
);

ALTER TABLE "BOOK_OPTION" ADD CONSTRAINT "PK_BOOK_OPTION" PRIMARY KEY (
	"BOOK_NO",
	"OPTION_FL"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "FK_PAYMENT_TO_BOOK_1" FOREIGN KEY (
	"BOOK_CARD_NO"
)
REFERENCES "PAYMENT" (
	"CARD_NO"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "FK_MEMBER_TO_BOOK_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "FK_GUEST_TO_BOOK_1" FOREIGN KEY (
	"GUEST_NO"
)
REFERENCES "GUEST" (
	"GUEST_NO"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "FK_ROOM_TO_BOOK_1" FOREIGN KEY (
	"ROOM_NUM"
)
REFERENCES "ROOM" (
	"ROOM_NUM"
);

ALTER TABLE "ADD" ADD CONSTRAINT "FK_MEMBER_TO_ADD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "ROOM" ADD CONSTRAINT "FK_ROOM_TYPE_TO_ROOM_1" FOREIGN KEY (
	"ROOM_TYPE_NO"
)
REFERENCES "ROOM_TYPE" (
	"ROOM_TYPE_NO"
);

ALTER TABLE "ROOM" ADD CONSTRAINT "FK_ROOM_VIEW_TO_ROOM_1" FOREIGN KEY (
	"ROOM_VIEW_NO"
)
REFERENCES "ROOM_VIEW" (
	"ROOM_VIEW_NO"
);

ALTER TABLE "BOOK_OPTION" ADD CONSTRAINT "FK_BOOK_TO_BOOK_OPTION_1" FOREIGN KEY (
	"BOOK_NO"
)
REFERENCES "BOOK" (
	"BOOK_NO"
);




